set nocompatible
set runtimepath+=~/.vim/bundle/neobundle.vim/
call neobundle#begin(expand('~/.vim/bundle/'))

NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'MarcWeber/vim-addon-mw-utils'
NeoBundle 'Shougo/unite.vim'
NeoBundle 'Shougo/vimproc.vim', {'build': {'unix': 'make'}}
NeoBundle 'Shougo/vimshell.vim'
NeoBundle 'SirVer/ultisnips'
NeoBundle 'ap/vim-buftabline'
NeoBundle 'ervandew/supertab'
NeoBundle 'flazz/vim-colorschemes'
NeoBundle 'google/vim-codefmt'
NeoBundle 'google/vim-coverage'
NeoBundle 'google/vim-glaive'
NeoBundle 'google/vim-maktaba'
NeoBundle 'gregsexton/MatchTag'
NeoBundle 'hynek/vim-python-pep8-indent'
NeoBundle 'kien/ctrlp.vim'
NeoBundle 'luochen1990/rainbow'
NeoBundle 'majutsushi/tagbar'
NeoBundle 'mhinz/vim-signify'
NeoBundle 'plasticboy/vim-markdown'
NeoBundle 'scrooloose/nerdtree'
NeoBundle 'sjl/gundo.vim'
NeoBundle 'tomtom/tlib_vim'
NeoBundle 'tpope/vim-abolish'
NeoBundle 'tpope/vim-afterimage'
NeoBundle 'tpope/vim-fugitive'
NeoBundle 'tpope/vim-surround'
NeoBundle 'vim-scripts/TeTrIs.vim'

call neobundle#end()

filetype plugin indent on
NeoBundleCheck

let mapleader=";"
let localleader="'"
let g:EclimCompletionMethod = 'omnifunc'
let g:UltiSnipsExpandTrigger = "<c-j>"
let g:UltiSnipsJumpBackwardTrigger = "<c-k>"
let g:UltiSnipsJumpForwardTrigger = "<c-j>"
let g:airline#extensions#tabline#enabled = 1
let g:buftabline_indicators = 1
let g:clang_format#command = 'clang-format-3.5'
let g:gundo_close_on_revert=1
let g:gundo_right=1
let g:rainbow_active = 1
let g:vimshell_prompt = '> '
let g:vimshell_right_prompt = ''
let g:vimshell_user_prompt = 'fnamemodify(getcwd(), ":~")'
let g:ycm_confirm_extra_conf = 0
let g:ycm_global_ycm_extra_conf = '~/.vim/ycm_extra_conf.py'

syntax enable

set autoread
set autowrite
set background=dark
set backspace=indent,eol,start 
set backupdir=~/.vim/genfiles/backup
set cindent
set cmdwinheight=1
set cursorline
set encoding=utf8
set expandtab
set fillchars+=vert:\ 
set foldlevelstart=20
set foldmethod=syntax
set hidden
set history=700
set incsearch
set linebreak
set nostartofline
set noswapfile
set nowrap
set number
set relativenumber
set ruler
set shiftwidth=2
set showcmd
set smartcase
set smarttab
set so=5
set tabstop=2
set undodir=~/.vim/genfiles/undo
set undofile
set undolevels=1000         " How many undos
set undoreload=10000        " number of lines to save for undo
set viminfo+=n~/.vim/genfiles/viminfo
set whichwrap+=<,>,h,l
set wildignore=*.o,*~,*.pyc
set wildmenu

cnoremap <c-w> <home>\<<end>\>
inoremap jk <esc>
nnoremap <backspace> <<
nnoremap <c-c> "+yy
nnoremap <c-v> "+p
nnoremap <leader>; ;
nnoremap <leader><tab> mzgg=G'z
nnoremap <leader>a <c-a>
nnoremap <leader>b :TagbarToggle<cr>
nnoremap <leader>b!c :bd!<cr>
nnoremap <leader>bc :bd<cr>
nnoremap <leader>f :FormatCode<cr>
nnoremap <leader>flip :set arabic!<cr>
nnoremap <leader>flip :set arabic!<cr>
nnoremap <leader>g :GundoToggle<cr>
nnoremap <leader>h <c-w>h
nnoremap <leader>j <c-w>j 
nnoremap <leader>k <c-w>k
nnoremap <leader>l <c-w>l
nnoremap <leader>n :NERDTreeToggle<cr>
nnoremap <leader>ss :set hlsearch!<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>
nnoremap <leader>tn :echom "BAD."<cr>
nnoremap <leader>v <c-v>
nnoremap <leader>vs :VimShellTab<cr>
nnoremap <space> :
nnoremap <tab> >>
nnoremap H :bprev<cr>
nnoremap J <c-d>
nnoremap K <c-u>
nnoremap L :bnext<cr>
vnoremap <c-c> "+y
vnoremap <c-v> "+p
vnoremap u <nop>

highlight CursorColumn cterm=NONE ctermbg=darkred ctermfg=white guibg=darkred guifg=white
highlight CursorLine   cterm=NONE ctermbg=darkred ctermfg=white guibg=darkred guifg=white
highlight Pmenu ctermbg=darkgrey ctermfg=white
highlight PmenuSbar ctermbg=cyan ctermfg=green
highlight PmenuSel ctermbg=darkblue ctermfg=green
highlight PmenuThumb ctermbg=white ctermfg=red

colo molokai
